In [1]:
import numpy as np

def normalize(x):
    idx = np.abs(x).argmax()
    fac = x[idx]
    x_n = x / fac
    return fac, x_n

def power_iteration(A, n, tol=1e-13, maxiter=100):
    """
    Performs power iteration using max norm. Computes the eigenvector corresponding to the largest eigenvalue of a matrix.

    Parameters
    ----------
    A : numpy.ndarray
        The matrix to compute the eigenvector of
    n : int
        The size of the matrix
    tol : float
        The tolerance for the stopping criterion
    maxiter : int
        The maximum number of iterations

    Returns
    -------
    float
        The eigenvalue
    numpy.ndarray
        The eigenvector
    """
    x = np.random.rand(n)
    fac, x = normalize(x)
    for i in range(maxiter):
        x_new = np.dot(A, x)
        fac, x_new = normalize(x_new)
        if np.linalg.norm(x - x_new) < tol:
            return fac, x_new
        x = x_new
    raise ValueError("Power iteration did not converge")

def inverse_iteration(A, n, offset, tol=1e-13, maxiter=1000):
    """
    Performs inverse iteration using max norm. Computes the eigenvector corresponding to the smallest eigenvalue of a matrix. Can be used to compute the eigenvector corresponding to any eigenvalue by first offsetting the matrix.

    Parameters
    ----------
    A : numpy.ndarray
        The matrix to compute the eigenvector of
    n : int
        The size of the matrix
    offset : float
        The offset to apply to the matrix
    tol : float
        The tolerance for the stopping criterion
    maxiter : int
        The maximum number of iterations

    Returns
    -------
    float
        The eigenvalue
    numpy.ndarray
        The eigenvector
    """
    x = np.random.rand(n)
    fac, x = normalize(x)
    for i in range(maxiter):
        x_new = np.linalg.solve(A - offset * np.eye(n), x)
        fac_new, x_new = normalize(x_new)
        #print(x_new)
        if np.abs(fac - fac_new) < tol:
            print(i)
            return 1/fac, x_new
        x = x_new
        fac = fac_new

In [8]:
A = np.array(
    [[2,1,3],
     [1,1,2],
     [3,2,1]])
#ev, ex = np.linalg.eig(A)
#display("Eigenvalues:", ev)
#display("Eigenvectors:", ex)
#ev, ex = power_iteration(A, 3)
#display("Eigenvalue:", ev)
#display("Eigenvector:", ex)
A = A+1.5*np.eye(3)
ev, ex = np.linalg.eig(A)
display("Eigenvalues:", ev)
display("Eigenvectors:", ex)

ev, ex = inverse_iteration(A, 3, 0)
display("Eigenvalue:", ev)
display("Eigenvector:", ex)


'Eigenvalues:'

array([ 7.00330763,  1.88492837, -0.38823601])

'Eigenvectors:'

array([[-0.65597979, -0.5579224 , -0.5083435 ],
       [-0.42322179,  0.8295505 , -0.36432031],
       [-0.62495907,  0.02384471,  0.78029327]])

19


'Eigenvalue:'

-0.3882360088434148

'Eigenvector:'

array([-0.65147749, -0.46690177,  1.        ])